### ISSUE TITLE
Replay animation on the same route

### ISSUE THREAD

**Issue by nicolaschenet** [gigafied/ember-animate#32] opened 2014-12-05 11:54 UTC
Hello folks ;)

I'm facing an edge case. I currently display a list of meetings based on the route's dynamic segments.

```
this.resource('meetings', function () {
    this.route('list', { path: '/:year/week/:week' });
    this.resource('meeting', { path: ':meeting_id' });
  });
```

The route **list** is animated, and it plays well when I enter it for the first time. BUT, I would like to be able to *"replay"* the same animation when I navigate the same route with other values for the segments.

**Exampe**
Transitioning from `/meetings/2014/week/45` to `/meetings/2014/week/46` would replay the animation.

Do you think there's a way to do it ?

**Comment by gigafied** [comment] 2015-02-09 20:59
Closing this as it's a duplicate of issue #16

**Closed by gigafied** 2015-02-09 20:59 UTC
